version: '2'
services:
    gstocksoftit-app:
        image: gstocksoftit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gstocksoftit-mysql:3306/gstocksoftit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gstocksoftit-elasticsearch:9300
        ports:
            - 8080:8080
    gstocksoftit-mysql:
        extends:
            file: mysql.yml
            service: gstocksoftit-mysql
    gstocksoftit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gstocksoftit-elasticsearch
